/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : bigint,
  'role' : Role,
  'text' : string,
  'timestamp' : Time,
}
export interface Note { 'id' : bigint, 'content' : string, 'createdAt' : Time }
export interface Reminder {
  'id' : bigint,
  'title' : string,
  'done' : boolean,
  'createdAt' : Time,
  'description' : string,
}
export type Role = { 'user' : null } |
  { 'jarvis' : null };
export type Time = bigint;
export interface _SERVICE {
  'addMessage' : ActorMethod<[Role, string], bigint>,
  'addNote' : ActorMethod<[string], bigint>,
  'addReminder' : ActorMethod<[string, string], bigint>,
  'clearHistory' : ActorMethod<[], undefined>,
  'deleteNote' : ActorMethod<[bigint], boolean>,
  'deleteReminder' : ActorMethod<[bigint], boolean>,
  'getHistory' : ActorMethod<[], Array<Message>>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'markDone' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];