/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({ 'user' : IDL.Null, 'jarvis' : IDL.Null });
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'role' : Role,
  'text' : IDL.Text,
  'timestamp' : Time,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Time,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'done' : IDL.Bool,
  'createdAt' : Time,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([Role, IDL.Text], [IDL.Nat], []),
  'addNote' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addReminder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'clearHistory' : IDL.Func([], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteReminder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'markDone' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({ 'user' : IDL.Null, 'jarvis' : IDL.Null });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'role' : Role,
    'text' : IDL.Text,
    'timestamp' : Time,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Time,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'done' : IDL.Bool,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([Role, IDL.Text], [IDL.Nat], []),
    'addNote' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addReminder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'clearHistory' : IDL.Func([], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteReminder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'markDone' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };